### ISSUE TITLE
do not have any debug

### ISSUE THREAD

**Issue by jyjxqy** [fblupi/3DCurator#108]
I appreciate that you upload this project on github, but I found some problems when I tried to run it. I found that there were not any debug, but the dll files in my PC are all debugs. Could you help me with this?

**Comment by jyjxqy** [comment]
I mean that the project only has a release motion, so I cannot run it.

**Comment by fblupi** [comment]
I had several issues running the project with debug libraries. That's why I only use release libraries. It's easy to have both of them installed on your PC. You only have to change the path to point the one you want to use. Check it and tell me if you have any issues.
